#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DEFAULT_BASE_BRANCH="master"
DEFAULT_SYNC_BRANCH="upstream-sync"
UPSTREAM_REF="upstream/master"

BASE_BRANCH="${BASE_BRANCH:-$DEFAULT_BASE_BRANCH}"
SYNC_BRANCH="${SYNC_BRANCH:-$DEFAULT_SYNC_BRANCH}"
PUSH_BRANCH=0
OPEN_PR=0

usage() {
  echo "Usage: $0 [--push] [--pr]"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --push)
      PUSH_BRANCH=1
      shift
      ;;
    --pr)
      OPEN_PR=1
      PUSH_BRANCH=1
      shift
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

cd "$ROOT_DIR"

require_clean_tracked_worktree() {
  if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "Refusing to run with tracked-file changes in the worktree."
    echo "Commit or stash tracked changes first."
    exit 1
  fi
}

warn_on_untracked_files() {
  local untracked
  untracked="$(git ls-files --others --exclude-standard)"
  if [[ -n "$untracked" ]]; then
    echo "Warning: untracked files are present and will be left untouched:"
    echo "$untracked"
    echo
  fi
}

require_remote() {
  local remote_name="$1"
  if ! git remote get-url "$remote_name" >/dev/null 2>&1; then
    echo "Missing required git remote: $remote_name"
    exit 1
  fi
}

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Missing required command: $command_name"
    exit 1
  fi
}

get_github_repo_from_origin() {
  local origin_url repo
  origin_url="$(git remote get-url origin)"

  case "$origin_url" in
    git@*:*/*.git)
      repo="${origin_url#*:}"
      repo="${repo%.git}"
      ;;
    git@*:*/*)
      repo="${origin_url#*:}"
      ;;
    https://github.com/*/*.git)
      repo="${origin_url#https://github.com/}"
      repo="${repo%.git}"
      ;;
    https://github.com/*/*)
      repo="${origin_url#https://github.com/}"
      ;;
    *)
      echo "Unable to derive GitHub repo from origin URL: $origin_url"
      exit 1
      ;;
  esac

  printf '%s\n' "$repo"
}

echo "==> repo: $ROOT_DIR"
echo "==> base branch: $BASE_BRANCH"
echo "==> sync branch: $SYNC_BRANCH"

require_remote origin
require_remote upstream
require_clean_tracked_worktree
warn_on_untracked_files

GH_REPO=""
if [[ $OPEN_PR -eq 1 ]]; then
  require_command gh
  GH_REPO="$(get_github_repo_from_origin)"
  echo "==> GitHub repo: $GH_REPO"
fi

echo "==> fetching remotes"
git fetch origin
git fetch upstream

echo "==> updating local $BASE_BRANCH from origin/$BASE_BRANCH"
git checkout "$BASE_BRANCH"
git pull --ff-only origin "$BASE_BRANCH"

echo "==> creating/resetting $SYNC_BRANCH from $BASE_BRANCH"
git checkout -B "$SYNC_BRANCH" "$BASE_BRANCH"

echo "==> merging $UPSTREAM_REF into $SYNC_BRANCH"
git merge "$UPSTREAM_REF"

if [[ $PUSH_BRANCH -eq 1 ]]; then
  echo "==> pushing $SYNC_BRANCH to origin"
  if git ls-remote --exit-code --heads origin "$SYNC_BRANCH" >/dev/null 2>&1; then
    git push origin "$SYNC_BRANCH"
  else
    git push -u origin "$SYNC_BRANCH"
  fi
fi

if [[ $OPEN_PR -eq 1 ]]; then
  echo "==> checking for existing PR from $SYNC_BRANCH into $BASE_BRANCH"
  existing_pr_url="$(gh pr list -R "$GH_REPO" --head "$SYNC_BRANCH" --base "$BASE_BRANCH" --json url --jq '.[0].url // ""')"

  if [[ -n "$existing_pr_url" ]]; then
    echo "Existing PR found:"
    echo "  $existing_pr_url"
  else
    echo "==> creating PR"
    gh pr create \
      -R "$GH_REPO" \
      --base "$BASE_BRANCH" \
      --head "$SYNC_BRANCH" \
      --title "Sync upstream/master into $BASE_BRANCH" \
      --body "Automated upstream sync branch generated by \`scripts/upstream_sync.sh\`."
  fi
fi

echo
echo "Upstream sync branch updated successfully."
echo
echo "Next steps:"
echo "  1. Review the diff:"
echo "     git diff $BASE_BRANCH..$SYNC_BRANCH"
echo
echo "  2. Run validation:"
echo "     ruff check opendbc"
echo "     ty check opendbc"
echo "     python -m unittest opendbc.safety.tests.test_turbo"
echo
if [[ $PUSH_BRANCH -eq 1 ]]; then
  if [[ $OPEN_PR -eq 1 ]]; then
    echo "  3. Review the PR from $SYNC_BRANCH into $BASE_BRANCH"
  else
    echo "  3. Open a PR from $SYNC_BRANCH into $BASE_BRANCH"
  fi
else
  echo "  3. Push the sync branch if it looks good:"
  echo "     git push -u origin $SYNC_BRANCH"
  echo
  echo "  4. Open a PR from $SYNC_BRANCH into $BASE_BRANCH"
fi
